//! Regression: the resource gate must actually see a busy CPU.
//!
//! `sysinfo` computes `cpu_usage()` as a delta between two refreshes. A refresh
//! that lands inside `MINIMUM_CPU_UPDATE_INTERVAL` of the previous one reports
//! 0.0% on every core no matter how loaded the box is. `ResourceGate::check()`
//! constructs a monitor and snapshots immediately, so before 2026-08-03 the
//! `max_cpu_load` threshold could never trip: a five-box zensysbench run gated
//! 0 of 205 cells while the dev box sat at load 17.
//!
//! These tests pin the fix from both ends — the raw monitor must report load,
//! and the gate built on top of it must refuse to pass a saturated box.

use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant};

/// Spin every core until the returned guard is dropped.
fn saturate() -> impl Drop {
    struct Stop(Arc<AtomicBool>, Vec<std::thread::JoinHandle<()>>);
    impl Drop for Stop {
        fn drop(&mut self) {
            self.0.store(true, Ordering::Relaxed);
            for h in self.1.drain(..) {
                let _ = h.join();
            }
        }
    }
    let stop = Arc::new(AtomicBool::new(false));
    let n = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(2);
    let handles = (0..n)
        .map(|_| {
            let stop = Arc::clone(&stop);
            std::thread::spawn(move || {
                let mut x = 0u64;
                while !stop.load(Ordering::Relaxed) {
                    // Enough work between checks that the atomic load is noise.
                    for i in 0..100_000u64 {
                        x = x.wrapping_add(i).wrapping_mul(2_654_435_761);
                    }
                    std::hint::black_box(x);
                }
            })
        })
        .collect();
    Stop(stop, handles)
}

/// All phases live in ONE test on purpose: cargo runs test fns concurrently, so
/// a separate "idle box" test would be measuring the load generated by the busy
/// test running beside it. (It did, on the first run — 0.997 against a 0.95
/// threshold.) System-state assertions cannot be parallelised.
#[test]
fn gate_sees_cpu_load() {
    // --- phase 1: a monitor constructed while the box is ALREADY busy must
    // report that on its very first snapshot. This is the regression: the real
    // caller is `ResourceGate::new(cfg).check()`, one snapshot, no warm-up.
    {
        let _busy = saturate();
        // Establish load before constructing, so a failure means "refreshed too
        // soon", not "no load yet" — mirroring a cron already running when the
        // gate is consulted.
        std::thread::sleep(Duration::from_millis(300));

        let monitor = zenbench::platform::SystemMonitor::new();
        let t0 = Instant::now();
        let state = monitor.snapshot();
        let elapsed = t0.elapsed();

        assert!(
            state.cpu_load > 0.10,
            "first snapshot reported cpu_load={:.3} while every core was \
             spinning — the monitor refreshed inside MINIMUM_CPU_UPDATE_INTERVAL \
             and read a zero delta (took {elapsed:?})",
            state.cpu_load
        );

        // --- phase 2: the gate built on that monitor must refuse the box.
        // max_wait is tiny because we are the ones holding it busy; waiting for
        // clear would just burn the timeout.
        let cfg = zenbench::GateConfig::default()
            .max_cpu_load(0.50)
            .max_wait(Duration::from_millis(1));
        assert!(
            zenbench::ResourceGate::new(cfg).check().is_some(),
            "gate passed a box with every core saturated — max_cpu_load is not \
             being enforced"
        );
    } // busy threads stop and join here

    // --- phase 3: the complement — the fix must not make the gate paranoid,
    // i.e. it must still compare against the threshold rather than always
    // blocking. Threshold 1.01 is deliberately unreachable (cpu_load is a
    // fraction ≤ 1.0), so this holds no matter how loaded the machine is.
    // Asserting on a "quiet" box instead would be flaky in CI, where cargo
    // runs test BINARIES concurrently and a sibling binary can peg every core.
    std::thread::sleep(Duration::from_millis(600)); // let our own spinners age out
    let cfg = zenbench::GateConfig::default()
        .max_cpu_load(1.01)
        .max_heavy_processes(usize::MAX)
        .min_available_ram_mb(0)
        .max_cpu_temp_c(None);
    if let Some(zenbench::GateReason::CpuLoad(load)) = zenbench::ResourceGate::new(cfg).check() {
        panic!(
            "gate blocked on CPU load {load:.3} against an unreachable 1.01 \
             threshold — the comparison is inverted or the threshold is ignored"
        );
    }
}
